# Generated by Django 4.2.7 on 2023-12-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
